from __future__ import annotations

from typing import Dict, List


# Versioned catalog for deterministic question/answer anchor extraction in raw text.
# Patterns are expected to run against normalized text (lowercase, accents removed).
ANCHORS: Dict[str, Dict[str, object]] = {
    "sistema_nome": {
        "section": "sistemas",
        "type": "table_row",
        "patterns": [
            r"\bnome\s+do\s+sistema\b",
            r"\bsistema\s+utilizado\b",
            r"\bsistema\s*:\s*[a-z0-9][a-z0-9\s\-_]{2,}\b",
            r"\bdatasul\b",
            r"\berp\b",
        ],
        "synonyms": ["datasul", "erp", "plataforma"],
    },
    "dados_menores": {
        "section": "processos",
        "type": "multi_line",
        "patterns": [
            r"\bmenor(?:es)?\s+de\s+18\s+anos\b",
            r"\bmenor(?:es)?\s+de\s+idade\b",
            r"\bdados\s+de\s+menor(?:es)?\b",
            r"\bfilhos?\s+menor(?:es)?\b",
            r"\bdependente(?:s)?\s+menor(?:es)?\b",
            r"\bcrianca(?:s)?\b",
            r"\badolescente(?:s)?\b",
            r"\bmenor(?:es)?\b",
        ],
        "synonyms": [
            "menor",
            "menores",
            "menor de idade",
            "menores de 18 anos",
            "dados de menores",
            "filhos menores",
            "dependentes menores",
            "crianca",
            "adolescente",
        ],
    },
    "sistema_fornecedor": {
        "section": "sistemas",
        "type": "table_row",
        "patterns": [
            r"\bfornecedor\s+do\s+sistema\b",
            r"\bfornecedor\s+deste\s+sistema\b",
            r"\bempresa\s+responsavel\s+pel[oa]\s+sistema\b",
            r"\bfabricante\s+do\s+sistema\b",
            r"\bprovedor\s+do\s+sistema\b",
            r"^\s*fornecedor\s*:\s*.+$",
            r"^\s*vendor\s*:\s*.+$",
        ],
        "synonyms": [
            "fabricante do sistema",
            "provedor do sistema",
            "empresa responsavel pelo sistema",
        ],
    },
    "sistema_web": {
        "section": "sistemas",
        "type": "single_line",
        "patterns": [
            r"\bsistema\s+web\b",
            r"\btrata-?se\s+de\s+um\s+sistema\s+web\b",
            r"\bacesso\s+web\b",
        ],
        "synonyms": ["browser", "online", "internet", "saas"],
    },
    "possui_contrato": {
        "section": "sistemas",
        "type": "single_line",
        "patterns": [
            r"\bpossui\s+contrato\b",
            r"\btem\s+contrato\b",
            r"\bcontrato\s+com\s+o\s+fornecedor\b",
        ],
        "synonyms": ["clausula", "instrumento contratual"],
    },
    "contrato_apresentado": {
        "section": "sistemas",
        "type": "multi_line",
        "patterns": [
            r"\bcontrato\s+apresentad[oa]\b",
            r"\benviar\s+copia\s+do\s+contrato\b",
            r"\bcopia\s+do\s+contrato\b",
        ],
        "synonyms": ["anexo contrato", "comprovacao contratual"],
    },
    "possui_nda": {
        "section": "areas",
        "type": "single_line",
        "patterns": [
            r"\bpossui\s+nda\b",
            r"\btermo\s+de\s+sigilo\b",
            r"\bcontrato\s+de\s+confidencialidade\b",
            r"\bnda\b",
        ],
        "synonyms": ["confidencialidade", "non disclosure"],
    },
    "hd_externo_pendrive": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bhd\s+externo\b",
            r"\bdisco\s+externo\b",
            r"\bpen\s*drive\b",
            r"\bpendrive\b",
            r"\bmidia\s+removivel\b",
            r"\busb\b",
        ],
        "synonyms": ["armazenamento externo", "dispositivo removivel"],
    },
    "hd_dispositivo_senha": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bsenha\b.*\b(hd|pen\s*drive|pendrive|usb|midia)\b",
            r"\bcriptograf(ad[oa]|ia)\b.*\b(hd|usb|pendrive|pen\s*drive)\b",
            r"\bbitlocker\b",
        ],
        "synonyms": ["senha no dispositivo", "protecao do dispositivo"],
    },
    "hd_armazenado_onde": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bonde\s+fica\s+(?:armazenad[oa]|guardad[oa])\b",
            r"\bonde\b.*\b(armazenad[oa]|guardad[oa]|fica|ficam)\b",
            r"\blocal(?:izacao)?\s+de\s+(?:armazenamento|guarda)\b(?:\s*[:\-|])?",
            r"\bguardad[oa]\b.*\b(armario|cofre|gaveta|sala|arquivo)\b",
        ],
        "synonyms": ["local de guarda", "onde fica guardado"],
    },
    "compart_rede": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bcompartilhamento\s+de\s+dados\s+na\s+rede\b",
            r"\brede\s+pessoal\s+interna\s+da\s+empresa\b",
            r"\bcompartilhamento\s+na\s+rede\b",
        ],
        "synonyms": ["intranet", "lan", "vpn", "fileserver"],
    },
    "politica_restricao_acesso": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bpolitica\b.*\b(acesso|restricao)\b",
            r"\bcontrole\s+de\s+acesso\b",
            r"\bgestao\s+de\s+acesso\b",
            r"\bperfil\s+de\s+acesso\b",
            r"\bacesso\b.*\bpor\s+area\b",
        ],
        "synonyms": ["acesso por perfil", "segregacao de acesso"],
    },
    "rede_protecao_senha": {
        "section": "areas",
        "type": "single_line",
        "patterns": [
            r"\bprotecao\s+por\s+senha\b",
            r"\brede\s+protegida\s+por\s+senha\b",
            r"\bcontrole\s+de\s+acesso\b",
        ],
        "synonyms": ["politica de senhas", "acesso restrito"],
    },
    "nuvem_criptografia": {
        "section": "areas",
        "type": "single_line",
        "patterns": [
            r"\bdados\s+sao\s+criptografad[oa]s?\b",
            r"\bcriptografad[oa]s?\s+na\s+nuvem\b",
            r"\buso\s+de\s+controles\s+criptograficos\b",
        ],
        "synonyms": ["encrypt", "chave criptografica"],
    },
    "compart_nuvem": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bnuvem\b",
            r"\bcloud\b",
            r"\bonedrive\b",
            r"\bsharepoint\b",
            r"\bgoogle\s+drive\b",
            r"\bdropbox\b",
        ],
        "synonyms": ["compartilhamento em nuvem", "armazenamento cloud"],
    },
    "forma_compart": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bcomo\s+e\s+esse\s+compartilhamento\b",
            r"\bforma\s+de\s+compartilhamento\b",
            r"\bcompartilhamento\b",
        ],
        "synonyms": ["api", "arquivo", "email", "portal"],
    },
    "compart_terceiros": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\bterceir[oa]s?\b",
            r"\bfornecedor(?:es)?\b",
            r"\bparceiro(?:s)?\b",
            r"\bprestador(?:es)?\s+de\s+servico\b",
        ],
        "synonyms": ["terceiros", "fornecedores", "parceiros"],
    },
    "transferencia_paises": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\btransferencia\s+internacional\s+de\s+dados\b",
            r"\bpara\s+quais\s+paises\b",
        ],
        "synonyms": ["fora do brasil", "cross-border"],
    },
    "transferencia_internacional": {
        "section": "areas",
        "type": "multi_line",
        "patterns": [
            r"\btransferencia\s+internacional\b",
            r"\bpara\s+o\s+exterior\b",
            r"\bfora\s+do\s+pais\b",
            r"\b(outro|outros)\s+paises\b",
        ],
        "synonyms": ["cross-border", "fora do brasil"],
    },
    "classificacao_documentos": {
        "section": "areas",
        "type": "single_line",
        "patterns": [
            r"\bclassificacao\s+de\s+documentos\b",
            r"\bclassificacao\s+da\s+informacao\b",
            r"\bclassificacao\s+documental\b",
            r"\bnivel\s+de\s+sigilo\b",
        ],
        "synonyms": [
            "classificacao documental",
            "classificacao da informacao",
            "informacao classificada",
            "uso interno",
            "documento confidencial",
            "documento restrito",
            "documento sigiloso",
            "documento publico",
        ],
    },
    "dados_pessoais": {
        "section": "processos",
        "type": "table_row",
        "patterns": [
            r"\btratamento\s+de\s+dados\s+pessoais\b",
            r"\bpossui\s+tratamento\s+de\s+dados\s+pessoais\b",
            r"\bdados\s+pessoais\s+tratad[oa]s?\b",
            r"\bdados\s+tratados\b",
            r"\bcategoria\s+dos\s+dados\b",
            r"\bquais\s+dados\s+sao\s+tratados\b",
        ],
        "synonyms": [
            "dados pessoais",
            "tratamento de dados pessoais",
            "dados tratados",
            "categoria dos dados",
            "cpf",
            "nome",
            "rg",
            "email",
            "telefone",
            "endereco",
            "data de nascimento",
        ],
    },
    "dados_tratados_quais": {
        "section": "processos",
        "type": "table_row",
        "patterns": [
            r"\bquais\s+dados\s+sao\s+utilizados\s+neste\s+processo\s+de\s+negocio\b",
            r"\bquais\s+dados\s+sao\s+tratados\b",
            r"\bquais\s+dados\s+pessoais\s+sao\s+tratados\b",
            r"\bquais\s+dados\s+sao\s+coletados\b",
            r"\bdados\s+utilizados\s+neste\s+processo\b",
        ],
        "synonyms": [
            "quais dados sao utilizados neste processo de negocio",
            "quais dados sao tratados",
            "quais dados sao coletados",
            "detalhamento dos dados tratados",
            "descricao do dado",
            "nome",
            "cpf",
            "rg",
            "email",
            "telefone",
            "endereco",
            "data de nascimento",
            "foto",
            "genero",
            "estado civil",
            "dados bancarios",
            "cnpj",
            "documento",
        ],
    },
    "dados_sensiveis": {
        "section": "processos",
        "type": "single_line",
        "patterns": [
            r"\bdados\s+sensiveis\b",
            r"\btratamento\s+de\s+dados\s+sensiveis\b",
        ],
        "synonyms": ["saude", "biometria", "religiao"],
    },
    "fisico_digital": {
        "section": "processos",
        "type": "single_line",
        "patterns": [
            r"\bfisico\s+ou\s+digital\b",
            r"\bfisico\/digital\b",
            r"\bpapel\s+ou\s+digital\b",
        ],
        "synonyms": ["impresso", "eletronico", "online"],
    },
    "armazenado_nuvem": {
        "section": "processos",
        "type": "single_line",
        "patterns": [
            r"\barmazenad[oa]\s+em\s+nuvem\b",
            r"\barmazenamento\s+em\s+nuvem\b",
        ],
        "synonyms": ["cloud", "saas", "storage"],
    },
    "compart_interno_terceiros": {
        "section": "processos",
        "type": "single_line",
        "patterns": [
            r"\bcompartilhamento\s+interno\s+ou\s+com\s+terceiros\b",
            r"\bcompartilhamento\s+com\s+terceiros\b",
        ],
        "synonyms": ["interno", "externo", "parceiros"],
    },
    "tempo_retencao": {
        "section": "processos",
        "type": "single_line",
        "patterns": [
            r"\btempo\s+necessario\b",
            r"\btempo\s+de\s+retencao\b",
            r"\bretencao\b",
            r"\bpermanente\b",
        ],
        "synonyms": ["prazo", "duracao", "anos"],
    },
    "formato_dados_disponiveis": {
        "section": "processos",
        "type": "multi_line",
        "patterns": [
            r"\bformato\s+dos\s+dados\s+disponiveis\b",
            r"\bformato\s+no\s+qual\s+os\s+dados\s+estao\s+disponiveis\b",
            r"\bmeio\s+em\s+que\s+os\s+dados\s+estao\s+disponiveis\b",
            r"\bsuporte\s+dos\s+dados\b",
        ],
        "synonyms": [
            "planilha",
            "e-mail",
            "email",
            "formulario",
            "documento",
            "word",
            "pdf",
            "arquivo",
            "pasta",
            "sistema",
            "software",
            "portal",
            "google drive",
            "onedrive",
            "pen drive",
            "digital",
            "fisico",
        ],
    },
    "medidas_admin_descritas": {
        "section": "processos",
        "type": "table_row",
        "patterns": [
            r"\bpolitic[ao]\b.*\bdocumental\b",
            r"\bpolitic[ao]\b.*\bacesso\b",
            r"\bprocedimento\b.*\bouvidoria\b",
            r"\bprocedimento\b.*\bgest[aã]o\b",
            r"\btreinamento\b.*\bacesso\b",
            r"\bhierarquia\s+de\s+acesso\b",
            r"\bpermitid[oa]\s+apenas\b",
            r"\bacesso\b.*\brestrit[oa]\b",
            r"\bexclusivamente\b.*\be-?mail\b",
            r"\bexclusivamente\b.*\bwhatsapp\b",
            r"\bprocesso\s+de\s+aceita[cç][aã]o\b",
        ],
        "synonyms": [
            "politica de organizacao documental",
            "politica de acesso",
            "procedimento",
            "treinamento de acesso",
            "hierarquia de acesso",
            "permitido apenas",
            "acesso restrito",
            "canal exclusivo",
            "exclusivamente por e-mail",
            "exclusivamente por whatsapp",
            "processo de aceitacao",
        ],
    },
    "forma_transferencia": {
        "section": "processos",
        "type": "multi_line",
        "patterns": [
            r"\bforma\s+como\s+os\s+dados\s+sao\s+transferidos\b",
            r"\bforma\s+de\s+transferencia\s+de\s+dados\b",
            r"\btransferencia\s+de\s+dados\b",
        ],
        "synonyms": ["api", "arquivo", "email", "sftp"],
    },
    "medidas_seg_descritas": {
        "section": "processos",
        "type": "table_row",
        "patterns": [
            r"\bcontrole\s+de\s+acesso\b",
            r"\bgestao\s+de\s+acesso\b",
            r"\bperfil\s+de\s+acesso\b",
            r"\bprotegid[oa]\s+por\s+senha\b",
            r"\bsenha\s+de\s+acesso\b",
            r"\bsenha\s+unica\b",
            r"\bacesso\b.*\brestrit[oa]\b",
            r"\barmario\s+trancad[oa]\b",
            r"\bsala\b.*\bfechad[oa]\b",
            r"\bfechad[oa]\s+diariamente\b",
        ],
        "synonyms": [
            "controle de acesso",
            "gestao de acesso",
            "perfil de acesso",
            "protegido por senha",
            "senha de acesso",
            "senha unica",
            "acesso restrito",
            "armario trancado",
            "sala fechada",
            "fechada diariamente",
        ],
    },
}


QUESTION_ANCHOR_MAP: Dict[str, List[str]] = {
    "1_HD_externo_pendrive": ["hd_externo_pendrive"],
    "1_1_hd_tem_senha": ["hd_dispositivo_senha"],
    "1_2_hd_armazenado_onde": ["hd_armazenado_onde"],
    "2_compart_dados_rede": ["compart_rede"],
    "2_1_rede_protecao_senha": ["rede_protecao_senha"],
    "2_2_politica_restricao_acesso": ["politica_restricao_acesso"],
    "3_compart_nuvem": ["compart_nuvem", "armazenado_nuvem"],
    "3_1_nuvem_criptografado": ["nuvem_criptografia"],
    "4_compart_terceiros": ["compart_terceiros", "forma_compart"],
    "4_1_forma_compart": ["forma_compart"],
    "4_2_termo_sigilo_terceiros": ["possui_nda"],
    "5_transfer_internacional": ["transferencia_internacional", "transferencia_paises"],
    "5_1_paises": ["transferencia_paises"],
    "5_2_termo_sigilo_transfer": ["possui_nda"],
    "6_classificacao_documentos": ["classificacao_documentos"],
    "2_trata_dados_pessoais": ["dados_pessoais"],
    "6_dados_tratados_quais": ["dados_tratados_quais"],
    "3_trata_dados_sensiveis": ["dados_sensiveis"],
    "6_1_fisico_ou_digital": ["fisico_digital"],
    "6_2_armazenado_nuvem": ["armazenado_nuvem"],
    "6_3_compart_interno_terceiros": ["compart_interno_terceiros"],
    "11_tempo_necessario_apenas": ["tempo_retencao"],
    "12_formato_dados_disponiveis": ["formato_dados_disponiveis", "fisico_digital", "forma_transferencia"],
    "13_forma_transferencia_dados": ["forma_transferencia"],
    "17_medidas_seg_cibernetica": ["medidas_seg_descritas"],
    "17_2_medidas_seg_descritas": ["medidas_seg_descritas"],
    "18_medidas_admin_protecao": ["medidas_admin_descritas"],
    "18_2_admin_descritas": ["medidas_admin_descritas"],
    "1_nome_identificado": ["sistema_nome"],
    "2_fornecedor_identificado": ["sistema_fornecedor"],
    "3_eh_web": ["sistema_web"],
    "4_possui_contrato": ["possui_contrato"],
    "4_1_contrato_apresentado": ["contrato_apresentado"],
    "4_dados_menores": ["dados_menores"],
}


# Hybrid retrieval lexical hints.
QUESTION_KEYWORDS: Dict[str, Dict[str, List[str]]] = {
    "1_nome_identificado": {
        "required": ["sistema"],
        "optional": ["nome","datasul", "erp", "plataforma", "software","totvs"],
        "negative": ["sem sistema", "nao identificado"],
    },
    "4_dados_menores": {
        "required": ["menor"],
        "optional": [
            "menores",
            "menor de idade",
            "menores de 18 anos",
            "dados de menores",
            "filhos menores",
            "dependentes menores",
            "crianca",
            "adolescente",
        ],
        "negative": [],
    },
    "4_1_contrato_apresentado": {
        "required": ["contrato"],
        "optional": ["copia", "enviar", "anexo", "apresentado"],
        "negative": ["nao apresentado", "sem contrato"],
    },
    "9_somente_quando_necessario": {
        "required": ["necessario"],
        "optional": [
            "estritamente necessarios",
            "somente quando necessario",
            "apenas quando necessario",
            "atinge o seu objetivo",
            "objetivo do processo",
            "minimizacao",
            "minimizacao de dados",
        ],
        "negative": ["sem criterio de necessidade", "sem necessidade"],
    },
    "6_classificacao_documentos": {
        "required": ["classificacao"],
        "optional": [
            "classificacao de documentos",
            "classificacao da informacao",
            "classificacao documental",
            "informacao classificada",
            "nivel de sigilo",
            "uso interno",
            "documento confidencial",
            "documento restrito",
            "documento sigiloso",
            "documento publico",
        ],
        "negative": [
            "dado pessoal",
            "dados pessoais",
            "dado sensivel",
            "dados sensiveis",
            "categoria dos dados",
            "classificacao do produto",
        ],
    },
    "11_tempo_necessario_apenas": {
        "required": ["tempo", "retencao"],
        "optional": ["prazo", "permanente", "anos", "duracao"],
        "negative": ["indeterminado sem criterio"],
    },
    "4_2_termo_sigilo_terceiros": {
        "required": ["nda", "sigilo", "confidencialidade", "termo"],
        "optional": ["clausula", "cláusula", "acordo", "nao se aplica", "n/a", "nao aplicavel", "nao informado", "n.d."],
        "negative": ["nao existe nda", "nao existe termo de sigilo", "sem confidencialidade"],
    },
    "5_2_termo_sigilo_transfer": {
        "required": ["nda", "sigilo", "confidencialidade", "termo"],
        "optional": ["clausula", "cláusula", "acordo", "nao se aplica", "n/a", "nao aplicavel", "nao informado", "n.d."],
        "negative": ["nao existe nda", "nao existe termo de sigilo", "sem confidencialidade"],
    },
    "2_compart_dados_rede": {
        "required": ["compart", "rede"],
        "optional": ["interna", "intranet", "rede interna", "rede corporativa", "rede pessoal interna", "lan", "vpn"],
        "negative": ["nao compartilha na rede"],
    },
    "4_1_forma_compart": {
        "required": ["compart"],
        "optional": ["email", "e-mail", "software", "api", "arquivo", "formulario", "impresso", "integracao", "rede"],
        "negative": ["sem compartilhamento"],
    },
    "2_trata_dados_pessoais": {
        "required": ["dados pessoais", "tratamento"],
        "optional": [
            "cpf",
            "nome",
            "rg",
            "email",
            "e-mail",
            "telefone",
            "endereco",
            "data de nascimento",
            "documento",
            "dados tratados",
            "categoria dos dados",
            "pessoal",
        ],
        "negative": [],
    },
    "6_dados_tratados_quais": {
        "required": ["dados"],
        "optional": [
            "detalhamento dos dados tratados",
            "descricao do dado",
            "descrição do dado",
            "nome",
            "nome completo",
            "cpf",
            "rg",
            "email",
            "e-mail",
            "telefone",
            "endereco",
            "data de nascimento",
            "foto",
            "genero",
            "gênero",
            "estado civil",
            "cargo",
            "funcao",
            "função",
            "dados bancarios",
            "dados bancários",
            "cnpj",
            "razao social",
            "documento",
            "dados tratados",
            "dados utilizados",
            "dados coletados",
            "categoria dos dados",
        ],
        "negative": [],
    },
    "3_trata_dados_sensiveis": {
        "required": ["categoria"],
        "optional": ["pessoal", "sensivel", "dados pessoais", "dados sensiveis"],
        "negative": [],
    },
    "5_descricao_processo": {
        "required": ["processo"],
        "optional": ["entrevista", "admissao", "rescisao", "relatorio", "proposta"],
        "negative": [],
    },
    "6_1_fisico_ou_digital": {
        "required": ["digital"],
        "optional": ["fisico", "impresso", "papel", "email", "telefone", "banco de dados", "software", "sistema", "formulario"],
        "negative": [],
    },
    "4_possui_contrato": {
        "required": [
            "contrato com o fornecedor",
            "possui contrato escrito assinado",
            "contrato do sistema",
            "fornecedor do sistema",
        ],
        "optional": ["vendor", "provedor", "fabricante"],
        "negative": [
            "nao possui contrato",
            "execucao de contrato",
            "fichas contratuais",
            "setor juridico",
            "base legal",
        ],
    },
    "2_fornecedor_identificado": {
        "required": ["fornecedor"],
        "optional": ["vendor", "provedor", "fabricante"],
        "negative": ["sem fornecedor"],
    },
    "6_2_armazenado_nuvem": {
        "required": ["nuvem"],
        "optional": ["cloud", "armazenado", "storage"],
        "negative": ["nao armazenado em nuvem"],
    },
    "6_3_compart_interno_terceiros": {
        "required": ["compart", "terceiros"],
        "optional": ["interno", "externo", "parceiros", "rh", "rede pessoal interna", "rede interna"],
        "negative": ["nao ha compartilhamento"],
    },
    "6_4_descarte_apos_uso": {
        "required": ["descarte"],
        "optional": ["exclusao", "eliminacao", "retencao", "apos uso", "sempre"],
        "negative": [],
    },
    "12_formato_dados_disponiveis": {
        "required": [],
        "optional": [
            "digital",
            "fisico",
            "papel",
            "planilha",
            "formulario",
            "documento",
            "word",
            "pdf",
            "arquivo",
            "pasta",
            "email",
            "e-mail",
            "telefone",
            "whatsapp",
            "banco de dados",
            "sistema",
            "software",
            "portal",
            "google drive",
            "onedrive",
            "pen drive",
            "nuvem",
        ],
        "negative": [],
    },
    "13_forma_transferencia_dados": {
        "required": ["transferencia"],
        "optional": ["email", "e-mail", "rede interna", "intranet", "api", "arquivo", "software", "integracao"],
        "negative": [],
    },
    "14_processos_documentados": {
        "required": ["processo"],
        "optional": ["documentado", "processo interno", "relatorio", "proposta", "entrevista", "admissao", "rescisao"],
        "negative": [],
    },
    "17_medidas_seg_cibernetica": {
        "required": ["acesso"],
        "optional": [
            "gestao",
            "controle",
            "perfil",
            "restricao",
            "liderancas",
            "controller",
            "financeiro",
            "senha",
            "protegido por senha",
            "senha de acesso",
            "senha unica",
            "restrito",
            "armario trancado",
            "fechada diariamente",
        ],
        "negative": [],
    },
    "17_2_medidas_seg_descritas": {
        "required": ["acesso"],
        "optional": [
            "gestao",
            "controle",
            "perfil",
            "restricao",
            "liderancas",
            "controller",
            "financeiro",
            "senha",
            "protegido por senha",
            "senha de acesso",
            "senha unica",
            "restrito",
            "armario trancado",
            "fechada diariamente",
        ],
        "negative": [],
    },
    "18_medidas_admin_protecao": {
        "required": ["acesso"],
        "optional": ["gestao", "controle", "perfil", "restricao", "liderancas", "controller", "financeiro", "administrativo"],
        "negative": [],
    },
    "18_2_admin_descritas": {
        "required": ["acesso"],
        "optional": ["gestao", "controle", "perfil", "restricao", "liderancas", "controller", "financeiro", "administrativo"],
        "negative": [],
    },
}
