from __future__ import annotations

from typing import Dict, Any


DEFAULT_QUESTION_SCHEMA: Dict[str, Any] = {
    "type": "free_text",
    "allow_na": True,
    "allow_binary_signal": False,
    "min_tokens": 2,
    "required_terms": [],
    "forbidden_terms": [],
}


QUESTION_SCHEMA: Dict[str, Dict[str, Any]] = {
    # Areas
    "1_HD_externo_pendrive": {"type": "yes_no", "allow_na": False},
    "1_1_hd_tem_senha": {"type": "yes_no", "allow_na": False},
    "1_2_hd_armazenado_onde": {
        "type": "location",
        "allow_na": True,
        "min_tokens": 2,
        "required_terms": ["armario", "cofre", "gaveta", "sala", "local", "servidor", "nuvem", "arquivo"],
    },
    "2_compart_dados_rede": {"type": "yes_no", "allow_na": False},
    "2_1_rede_protecao_senha": {"type": "yes_no", "allow_na": False},
    "2_2_politica_restricao_acesso": {
        "type": "yes_no",
        "allow_na": False,
        "required_terms": [
            "acesso",
            "controle de acesso",
            "gestao de acesso",
            "perfil de acesso",
            "restricao",
            "segregacao",
            "liderancas",
            "controller",
            "financeiro",
        ],
    },
    "3_compart_nuvem": {"type": "yes_no", "allow_na": False},
    "3_1_nuvem_criptografado": {"type": "yes_no", "allow_na": False},
    "4_compart_terceiros": {"type": "yes_no", "allow_na": False},
    "4_1_forma_compart": {
        "type": "free_text",
        "allow_na": True,
        "min_tokens": 1,
        "required_terms": [
            "api",
            "email",
            "e-mail",
            "arquivo",
            "sftp",
            "ftp",
            "portal",
            "sistema",
            "software",
            "planilha",
            "formulario",
            "impresso",
            "integracao",
            "rede interna",
            "intranet",
        ],
    },
    "4_2_termo_sigilo_terceiros": {"type": "yes_no", "allow_na": True},
        "5_transfer_internacional": {"type": "yes_no", "allow_na": False},
    "5_1_paises": {
        "type": "list",
        "allow_na": True,
        "min_tokens": 2,
        "forbidden_terms": [
            "transferencia internacional",
            "transferência internacional",
            "fora do brasil",
            "fora do país",
            "fora do pais",
            "para o exterior",
            "cross-border",
        ],
    },
    "5_2_termo_sigilo_transfer": {
        "type": "yes_no",
        "allow_na": True,
        "required_terms": ["transfer", "internacional", "exterior", "fora do brasil", "fora do pais"],
    },
    "6_classificacao_documentos": {
        "type": "yes_no",
        "allow_na": False,
        "required_terms": [
            "classificacao de documentos",
            "classificacao da informacao",
            "classificacao documental",
            "informacao classificada",
            "nivel de sigilo",
            "uso interno",
            "documento confidencial",
            "documento restrito",
            "documento sigiloso",
            "documento publico",
        ],
        "forbidden_terms": [
            "dado pessoal",
            "dados pessoais",
            "dado sensivel",
            "dados sensiveis",
            "categoria dos dados",
            "categoria do dado",
            "classificacao do produto",
        ],
    },
    # Processos
    "1_decisoes_automatizadas": {"type": "yes_no", "allow_na": False},
    "2_trata_dados_pessoais": {
        "type": "free_text",
        "allow_na": False,
        "allow_binary_signal": True,
        "min_tokens": 1,
        "required_terms": [
            "dados pessoais",
            "cpf",
            "rg",
            "nome",
            "endereco",
            "email",
            "telefone",
            "data de nascimento",
            "matricula",
            "documento",
        ],
    },
    "3_trata_dados_sensiveis": {
        "type": "free_text",
        "allow_na": True,
        "allow_binary_signal": True,
        "min_tokens": 1,
        "required_terms": [
            "categoria",
            "pessoal",
            "sensivel",
            "dados pessoais",
            "dados sensiveis",
            "saude",
            "biometr",
            "relig",
            "orientacao sexual",
            "origem racial",
            "origem etnica",
            "opiniao politica",
            "sindical",
            "genet",
        ],
    },
    "4_dados_menores": {
        "type": "yes_no",
        "allow_na": False,
        "required_terms": [
            "menor",
            "menores",
            "menor de idade",
            "menores de 18 anos",
            "dados de menores",
            "filhos menores",
            "dependentes menores",
            "crianca",
            "adolescente",
        ],
    },
    "5_descricao_processo": {
        "type": "free_text",
        "allow_na": False,
        "min_tokens": 2,
        "required_terms": [
            "processo",
            "entrevista",
            "admissao",
            "rescisao",
            "relatorio",
            "proposta",
        ],
    },
    "6_dados_tratados_quais": {"type": "list", "allow_na": False, "min_tokens": 2},
    "6_1_fisico_ou_digital": {
        "type": "free_text",
        "allow_na": False,
        "min_tokens": 1,
        "required_terms": [
            "fisico",
            "digital",
            "papel",
            "eletronico",
            "online",
            "impresso",
            "email",
            "telefone",
            "banco de dados",
            "sistema",
            "software",
            "formulario",
        ],
    },
    "6_2_armazenado_nuvem": {"type": "yes_no", "allow_na": False},
    "6_3_compart_interno_terceiros": {"type": "yes_no", "allow_na": False},
    "6_4_descarte_apos_uso": {
        "type": "yes_no",
        "allow_na": True,
        "required_terms": ["exclusao", "eliminacao", "descarte", "retencao", "sempre"],
    },
    "7_finalidade_legitima": {"type": "yes_no", "allow_na": False},
    "8_finalidade_explicita_ao_titular": {"type": "yes_no", "allow_na": False},
    "9_somente_quando_necessario": {"type": "yes_no", "allow_na": False},
    "10_quem_usa_precisa": {"type": "yes_no", "allow_na": False},
    "11_tempo_necessario_apenas": {
        "type": "free_text",
        "allow_na": True,
        "min_tokens": 1,
        "required_terms": ["prazo", "tempo", "retencao", "permanente", "anos", "dias", "meses"],
    },
        "12_formato_dados_disponiveis": {
        "type": "free_text",
        "allow_na": False,
        "min_tokens": 1,
        "required_terms": [
            "digital",
            "fisico",
            "arquivo",
            "planilha",
            "documento",
            "word",
            "pdf",
            "sistema",
            "portal",
            "email",
            "e-mail",
            "whatsapp",
            "telefone",
            "banco de dados",
            "software",
            "formulario",
            "impresso",
            "pasta",
            "drive",
            "google drive",
            "onedrive",
            "pen drive",
            "nuvem",
        ],
    },
    "13_forma_transferencia_dados": {
        "type": "free_text",
        "allow_na": False,
        "min_tokens": 1,
        "required_terms": [
            "api",
            "email",
            "arquivo",
            "sftp",
            "ftp",
            "portal",
            "integracao",
            "webservice",
            "rede",
            "rede interna",
            "intranet",
            "software",
        ],
    },
    "14_processos_documentados": {
        "type": "yes_no",
        "allow_na": True,
        "required_terms": ["processo", "documentado", "relatorio", "proposta", "entrevista", "admissao", "rescisao"],
    },
    "15_dados_precisos_claros_atualizados": {"type": "yes_no", "allow_na": False},
    "16_titular_pode_corrigir": {"type": "yes_no", "allow_na": False},
    "17_medidas_seg_cibernetica": {
        "type": "yes_no",
        "allow_na": False,
        "required_terms": ["acesso", "controle", "gestao", "perfil", "restricao", "seguranca"],
    },
    "17_1_medidas_seg_comprovadas": {"type": "yes_no", "allow_na": False},
        "17_2_medidas_seg_descritas": {
        "type": "free_text",
        "allow_na": False,
        "min_tokens": 2,
        "required_terms": [
            "controle de acesso",
            "gestao de acesso",
            "perfil de acesso",
            "protegido por senha",
            "senha de acesso",
            "senha unica",
            "senha",
            "restrito",
            "armario trancado",
            "fechada diariamente",
            "backup",
            "antivirus",
            "antivírus",
            "firewall",
            "mfa",
        ],
    },
    "18_medidas_admin_protecao": {
        "type": "yes_no",
        "allow_na": False,
        "required_terms": [
            "acesso",
            "controle",
            "gestao",
            "perfil",
            "restricao",
            "administrativo",
            "politica",
            "procedimento",
            "treinamento",
            "hierarquia de acesso",
            "permitido apenas",
            "exclusivamente",
            "termo de adesao",
            "arquivado",
        ],
    },
    "18_1_admin_comprovadas": {"type": "yes_no", "allow_na": False},
    "18_2_admin_descritas": {
        "type": "free_text",
        "allow_na": False,
        "min_tokens": 2,
        "required_terms": [
            "acesso",
            "controle",
            "gestao",
            "perfil",
            "restricao",
            "administrativo",
            "politica",
            "procedimento",
            "treinamento",
            "hierarquia de acesso",
            "permitido apenas",
            "exclusivamente",
            "termo de adesao",
            "arquivado",
        ],
    },
    # Sistemas
    "1_nome_identificado": {"type": "free_text", "allow_na": False, "min_tokens": 1},
    "2_fornecedor_identificado": {"type": "free_text", "allow_na": False, "min_tokens": 1},
    "3_eh_web": {"type": "yes_no", "allow_na": False},
    "4_possui_contrato": {
        "type": "yes_no",
        "allow_na": True,
        "required_terms": ["contrato", "assinado", "fornecedor"],
    },
    "4_1_contrato_apresentado": {"type": "yes_no", "allow_na": True},
}
